#!/bin/bash

read -p "Enter the Walmart URL of the product: " url
interval=15

while true; do
    curl -s "$url" > webpage_content.txt
    if ! grep -q "Out of stock" webpage_content.txt; then
        afplay /System/Library/Sounds/Ping.aiff
    fi
    sleep $interval
done
